"""Word Unique contraint word and user id

Revision ID: faaa6dfb7936
Revises: dbbc5ac820c3
Create Date: 2021-02-28 16:34:04.077323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faaa6dfb7936'
down_revision = 'dbbc5ac820c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_word_user_uc', 'word', ['user_id', 'word'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_word_user_uc', 'word', type_='unique')
    # ### end Alembic commands ###
